In [14]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, roc_auc_score

In [23]:
data = pd.read_csv("Clean_Data_Classification.csv")
data_X = data.drop(columns='Sold')
data_Y = data['Sold']

In [27]:
X_Train, X_test, Y_train, Y_test = train_test_split(data_X, data_Y, train_size= 0.8)
logit_model = LogisticRegression(max_iter=1000)


In [26]:
logit_model.fit(X_Train, Y_train)


LogisticRegression(max_iter=1000)

In [5]:
Y_predicted = logit_model.predict(X_test)
print(Y_predicted)
Y_test_arr = np.array(Y_test)
print(Y_test_arr)

[0 0 0 1 1 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 1 0 1 0 0 0 1 0 1 0 0 0 1 1 0
 0 0 0 0 1 1 0 1 1 0 1 0 1 1 0 0 1 0 0 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 0 0
 1 1 0 1 0 0 1 0 1 1 0 0 0 0 0 1 0 0 0 1 1 1 1 1 1 0 1 0]
[1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 1 0 1 0 0 1 1 0 1 0 0 0 1 1 1 0 1 1 0 1 0
 0 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 1 0 1 0 0 1 0 0 0
 1 1 1 1 1 1 1 0 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 0]


In [6]:
prob_no_yes = logit_model.predict_proba(X_test)
print(prob_no_yes)

[[0.55340784 0.44659216]
 [0.75482978 0.24517022]
 [0.51590317 0.48409683]
 [0.38322758 0.61677242]
 [0.4860672  0.5139328 ]
 [0.76744802 0.23255198]
 [0.93298226 0.06701774]
 [0.56401821 0.43598179]
 [0.57230217 0.42769783]
 [0.85040084 0.14959916]
 [0.45353397 0.54646603]
 [0.64514944 0.35485056]
 [0.57248044 0.42751956]
 [0.44637394 0.55362606]
 [0.68956596 0.31043404]
 [0.40608207 0.59391793]
 [0.60437734 0.39562266]
 [0.76522722 0.23477278]
 [0.25290754 0.74709246]
 [0.65615987 0.34384013]
 [0.29096925 0.70903075]
 [0.44054948 0.55945052]
 [0.28732184 0.71267816]
 [0.69259444 0.30740556]
 [0.37707284 0.62292716]
 [0.50453452 0.49546548]
 [0.7679243  0.2320757 ]
 [0.58248649 0.41751351]
 [0.41845846 0.58154154]
 [0.76562712 0.23437288]
 [0.2855209  0.7144791 ]
 [0.53487133 0.46512867]
 [0.69164699 0.30835301]
 [0.54666461 0.45333539]
 [0.39749056 0.60250944]
 [0.25540983 0.74459017]
 [0.6816009  0.3183991 ]
 [0.69185759 0.30814241]
 [0.61733042 0.38266958]
 [0.58083748 0.41916252]


In [7]:
Y_predicted_02 = (prob_no_yes[:, 1] >= 0.4)
Y_predicted_02

array([ True, False,  True,  True,  True, False, False,  True,  True,
       False,  True, False,  True,  True, False,  True, False, False,
        True, False,  True,  True,  True, False,  True,  True, False,
        True,  True, False,  True,  True, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False,  True,  True, False, False,  True,
       False, False, False,  True,  True,  True, False,  True,  True,
       False, False,  True, False,  True, False, False,  True,  True,
       False, False,  True,  True,  True,  True, False, False,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False])

In [8]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_predicted)

array([[40, 11],
       [20, 31]], dtype=int64)

In [9]:
confusion_matrix(Y_test, Y_predicted_02)

array([[29, 22],
       [10, 41]], dtype=int64)

In [13]:
print(precision_score(Y_test, Y_predicted_02))
print(recall_score(Y_test, Y_predicted_02))
print(roc_auc_score(Y_test, Y_predicted_02))


0.6507936507936508
0.803921568627451
0.6862745098039216
