In [8]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [9]:
data = pd.read_csv("Clean_Data_Classification.csv")
data_X = data.drop(columns='Sold')
data_Y = data['Sold']

In [10]:
X_Train, X_test, Y_train, Y_test = train_test_split(data_X, data_Y, train_size= 0.8)
logit_model = LogisticRegression(max_iter=1000)

In [11]:
logit_model.fit(X_Train, Y_train)

LogisticRegression(max_iter=1000)

In [12]:
Y_predicted = logit_model.predict(X_test)
print(Y_predicted)
Y_test_arr = np.array(Y_test)
print(Y_test_arr)

[0 0 0 1 1 0 0 1 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1
 0 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 1 0 1 0 0 1
 0 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0 0 0 0 1 1 0 1 1 0 0 1]
[1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 1 0 1
 0 0 1 1 1 1 1 1 0 0 0 0 0 1 1 0 0 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1
 1 1 1 1 0 0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 1 1 0 1 1 0 0 0]


In [14]:
prob_no_yes = logit_model.predict_proba(X_test)
print(prob_no_yes)

[[0.7230615  0.2769385 ]
 [0.60265632 0.39734368]
 [0.80316116 0.19683884]
 [0.38903081 0.61096919]
 [0.37710165 0.62289835]
 [0.77268063 0.22731937]
 [0.77334025 0.22665975]
 [0.22382811 0.77617189]
 [0.50311853 0.49688147]
 [0.41269909 0.58730091]
 [0.81880616 0.18119384]
 [0.68058022 0.31941978]
 [0.68128233 0.31871767]
 [0.47736255 0.52263745]
 [0.26514731 0.73485269]
 [0.69111767 0.30888233]
 [0.44476636 0.55523364]
 [0.51294346 0.48705654]
 [0.61911486 0.38088514]
 [0.50848786 0.49151214]
 [0.71827936 0.28172064]
 [0.59777226 0.40222774]
 [0.57329814 0.42670186]
 [0.87707245 0.12292755]
 [0.64119062 0.35880938]
 [0.45379286 0.54620714]
 [0.38178291 0.61821709]
 [0.44011708 0.55988292]
 [0.24192159 0.75807841]
 [0.88674817 0.11325183]
 [0.32920604 0.67079396]
 [0.15183282 0.84816718]
 [0.6404801  0.3595199 ]
 [0.6930525  0.3069475 ]
 [0.5116444  0.4883556 ]
 [0.53567657 0.46432343]
 [0.42504616 0.57495384]
 [0.5805057  0.4194943 ]
 [0.58832045 0.41167955]
 [0.49913105 0.50086895]


In [19]:
Y_predicted_02 = (prob_no_yes[:, 1] >= 0.4)
Y_predicted_02

array([False, False, False,  True,  True, False, False,  True,  True,
        True, False, False, False,  True,  True, False,  True,  True,
       False,  True, False,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True,  True, False, False,  True, False,  True,
        True, False, False,  True,  True, False, False,  True, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True, False,  True, False,  True, False,  True,  True,
       False,  True,  True, False,  True,  True, False,  True,  True,
       False, False,  True])

In [17]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_predicted)

array([[39, 14],
       [20, 29]], dtype=int64)

In [20]:
confusion_matrix(Y_test, Y_predicted_02)

array([[28, 25],
       [13, 36]], dtype=int64)